we-are-number-1/yumble

- backend/src/index.js
- frontend/package-lock.json
- frontend/package.json
Added connection to mongodb atlas.
Added axios.
> DB Setup and added axios

- backend/.eslintrc.js
Added a new rule in backend/eslintc.js to ignore linebreak style.
> [FEAT] Add new eslint rule to ignore linebreak in backend/.eslintrc.js

- backend/src/__tests__/exampleTestSum.test.js
- backend/src/exampleTestSum.js
Added JSDocs to example method, to avoid linter issues.
> [BUG] Add JSDoc to exampleTestSum

- backend/src/index.js
- frontend/.eslintrc.js
- frontend/src/components/ExampleTestButton/Button.js
- frontend/src/components/ExampleTestButton/__test__/Button.test.js
added new ex lint rule and fixed eslint errors
> [BUG] Modify Eslint rules for react/propTypes

- .github/workflows/node.js.yml
- backend/.eslintrc.js
- backend/babel.config.js
- frontend/.eslintrc.js
> [FEAT] Added linting to GitHub actions

- CONTRIBUTING.md
added in the CONTRIBUTING readme a schema for Issue, PR and commit.
> [WIKI] Add Issue and PR schema to how to contribute

- backend/src/domain/Games.js
Changed the newGame() method in Games.js to use the set() method provided by the Map data structure
> [BUG] Modify newGame method in Games.js in the frontend

- backend/src/domain/models/Game.js
- frontend/src/sockets/endGame.js
- frontend/src/sockets/index.js
Recreated old branch, which closed the last PR.
> [FEAT] Add game end web socket to backend and frontend 

- backend/src/domain/Games.js
- backend/src/domain/models/Game.js
- backend/src/index.js
- backend/src/sockets/index.js
- backend/src/sockets/start.js
- frontend/src/sockets/endGame.js
- frontend/src/sockets/index.js
- frontend/src/sockets/nextRound.js
- frontend/src/sockets/start.js
Added next_round and start websockets to frontend and backend. To handle when the game should start, and when every round occurs.
> [FEAT] Add next round web socket to the backend and frontend

- backend/src/domain/Games.js
- backend/src/sockets/disconnect.js
Modify disconnect game in backend to remove user from game and remove game when there are 0 users.
> [FEAT] Modify disconnect game in backend

- backend/src/domain/Games.js
- backend/src/domain/models/Game.js
- backend/src/domain/models/SocketSession.js
- backend/src/index.js
- backend/src/sockets/disconnect.js
- backend/src/sockets/joinRoom.js
- backend/src/sockets/start.js
- frontend/src/sockets/endGame.js
- frontend/src/sockets/joinRoom.js
- frontend/src/sockets/start.js
Changed the naming in all the web sockets to have consistent and descriptive names.
> [FEAT] Modify web sockets to use consistent naming

- frontend/src/App.css
Added a hover to the `Back` and `View on Google Maps` buttons so that they change colour
Addresses issue #117
> [BUG] Fixed hover on back button

- backend/src/domain/models/SocketSession.js
Fixed typo in SocketSession constructor.
> [BUG] Modified constructor parameter to match field in SocketSession

- backend/src/domain/models/__tests__/SocketSession.test.js
Added tests for the SocketSession model, specifically adding a user and removing a user from the session.
> [TEST] Add Test for domain/models/SocketSession.js

- frontend/src/index.js
- frontend/src/sockets/SocketContext.js
Create socket context for frontend to persist a single socket connection at one time for a client
> [FEAT] Add Socket Context to App.js frontend

- backend/package-lock.json
- backend/package.json
- backend/src/domain/__mocks__/Games.js
- backend/src/sockets/__tests__/joinRoom.test.js
- backend/src/sockets/joinRoom.js
Added Unit Tests test for sockets/joinRoom.js
Mocks created:
__mocks__/Games.js
Added Socket.io-client library to backend for testing purposes
Fixed a bug in socket/joinRoom.js
Ref: https://medium.com/@tozwierz/testing-socket-io-with-jest-on-backend-node-js-f71f7ec7010f
https://jestjs.io/docs/mock-functions#using-a-mock-function
> [TEST] Added Mock tests for joinRoom.js backend socket

- frontend/src/sockets/SocketContext.js
Fixes issue with SocketContext in frontend.
> [BUG] Modify SocketContext io state inital value in frontend

- backend/src/index.js
- backend/src/sockets/__tests__/disconnect.test.js
- backend/src/sockets/disconnect.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/sockets/__tests__/setPreferences.test.js
- frontend/src/sockets/__tests__/start.test.js
Test frontend sockets: setPreferences, start
Test backend sockets: disconnect, joinRoom
> [TEST] Add socket tests for backend and frontend

- backend/src/domain/models/SocketSession.js
- backend/src/index.js
- backend/src/sockets/__tests__/disconnect.test.js
- backend/src/sockets/disconnect.js
now when the user disconnects from the lobby it also updates for the other users
> [FEAT] Add user disconnect socket lobby sync

- frontend/src/components/Common/getRestaurantCards.js
Removed the function call. Should work as expected now.
> [BUG] Fixing the redundant function call in getRestaurantCards that breaks the workflow

- frontend/src/components/Common/getAPIKey.js
- frontend/src/components/Common/getRestaurantCards.js
Card generation was halting due to image processing and foursquare API bugs.
> [BUG] Fixed card generation and foursquare api bugs.

- backend/src/domain/models/Game.js
- backend/src/index.js
- frontend/src/App.js
- frontend/src/components/5.Lobby/Lobby.js
- frontend/src/components/6.Countdown/CountDown.js
Go button in lobby room moves all users to countdown screen.
Amount of time for countdown is now obtained from backend
after countdown all users removed to next screen.
> [FEAT] Add integration for lobby and countdown rooms

- backend/src/index.js
- frontend/src/components/4.Preferences/Preferences.js
Fixed by adding API router and readding function calls to the index.js and preferences.js files.
> [BUG] Fixed restaurant card generation due to 404 error when calling foursquare API

- frontend/src/components/Common/getRestaurantCards.js
> [FEAT] Added coords data to restaurant cards so maps can be easily done

- .github/ISSUE_TEMPLATE/bug-report-template.md
- .github/ISSUE_TEMPLATE/ticket-schema.md
- .github/pull_request_template.md
Added a PR template, and slightly modified the existing templates for issues and bugs.
Closes #209
> [WIKI] Pull Request template & misc template changes made

- backend/src/domain/models/Game.js
- backend/src/domain/models/SocketSession.js
- backend/src/domain/models/__tests__/Game.test.js
- backend/src/domain/models/__tests__/SocketSession.test.js
- backend/src/mongo/models/__mocks__/Session.js
Created tests for domain/models/Game.js and domain/models/SocketSession.js.
Required to create mock for mongo/models/session.js
Note: Game.js requires socket.io client and other socket functions
> [TEST] Add Tests and Mocks for domain/models/.* in Backend

- frontend/src/sockets/__tests__/countdown.test.js
- frontend/src/sockets/__tests__/invalidCode.test.js
- frontend/src/sockets/__tests__/leaveRoom.test.js
- frontend/src/sockets/__tests__/setRestaurants.test.js
- frontend/src/sockets/__tests__/updateRestaurants.test.js
- frontend/src/sockets/__tests__/vote.test.js
- frontend/src/sockets/vote.js
name: [TEST] Add Test for new Sockets
about: added socket tests for invalid_code, leave_room, set_restaurant, update_restaurant, and vote in the frontend
title: [TEST] Add Test for new Sockets
labels: [frontend] [websockets]
assignees: afei088
> [TEST] Add Test for new Sockets

- backend/src/routes/__tests__/sessions.test.js
> [TEST] Add test for API PATCH
